spring.application.name=RouteNetLKServerApplication

spring.datasource.url=jdbc:mysql://localhost:3306/routenetlk
spring.datasource.username=root
spring.datasource.password=1234

spring.mvc.format.date=yyyy-MM-dd


