spring.application.name=RouteNetLKServerApplication

spring.datasource.url=jdbc:mysql://localhost:3306/routenetlk
spring.datasource.username=root
spring.datasource.password=1234

spring.mvc.format.date=yyyy-MM-dd

logging.level.org.optaplanner.core.impl.constructionheuristic=DEBUG
logging.level.org.optaplanner.core.impl.phase=DEBUG

# JWT Configuration
jwt.secret=M2s5Zkoybm1QOHZSNWBXN3hUMXFMNHlVNmhCMHpDOGVBOXNEMmZHNWpIN2tO
jwt.expiration=86400000

# In-Memory Admin User
spring.security.user.name=admin
spring.security.user.password=AdminPassword@2025

# CORS Configuration
app.cors.allowed-origins=http://localhost:4200

# Security Configuration
security.login.max-attempts=5
security.login.block-duration-minutes=15


# Logging
logging.level.lk.ashan.routenetlkserverapllication=DEBUG
logging.level.org.springframework.security=DEBUG

# Optional: To see the solving progress in your console
logging.level.ai.timefold.solver=INFO


