# Production Profile Configuration
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false

# Production Logging Levels
logging.level.root=WARN
logging.level.lk.ashan.routenetlkserverapllication=INFO
logging.level.org.springframework.security=WARN
